spring.application.name=drop-auth



server.port=8082

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/drop-auth
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info


# ==============================
# JWT
# ==============================

drop.jwt.secret=dropSuperSecretKeyForDevelopmentOnlyChangeThisToALongRandomSecretKey123456789

drop.jwt.expiration=86400000
